### ISSUE TITLE
Catcore does not read input from secondary channels after a restart

### ISSUE THREAD

**Issue by Idlebawb** [ErisApps/ChatCore#40]
Hi I've noticed an issue with catcore 1.0.0 not reading chat input from secondary twitch channels after restarting the game, but will still post messages to all channels.

Used Game / Mods:
Beat Saber 1.21.0
Catcore 1.0.0
Song Request Manager 2.15.8 (https://github.com/Krayn/SongRequestManager/releases/tag/2.15.8)
Link 1.0.3 (https://github.com/Auros/Link) Self compiled from latest code

Steps to reproduce:
- Start the Game
- Login to Twitch in the catcore browser config tool
- Add a secondary channel
- try !link or !bsr commands on both channels

Everything works up until here

- Restart the game
- SRM will post its startup notifications to both channels
- no reaction to either !bsr or !link commands on secondary channel
- still accepts input from main channel and will respond to both
- can still post to secondary channel using SRM keyboard

A workaround that seems to work every time:
- After restarting the game: Delete the secondary channel from the config and save
- Readd the secondary channel and save
- both SRM and Link pick up inputs from the secondary channel again

Full Mod Info:
[INFO @ 19:51:12 | IPA] Game version 1.21.0
[INFO @ 19:51:12 | IPA] -----------------------------
[INFO @ 19:51:12 | IPA] Loading plugins from Plugins and found 51
[INFO @ 19:51:12 | IPA] -----------------------------
[INFO @ 19:51:12 | IPA] Beat Saber IPA (BSIPA): 4.2.2
[INFO @ 19:51:12 | IPA] SiraUtil (SiraUtil): 3.0.6
[INFO @ 19:51:12 | IPA] websocket-sharp (websocket-sharp): 1.0.4
[INFO @ 19:51:12 | IPA] HttpSiraStatus (HttpSiraStatus): 7.1.4
[INFO @ 19:51:12 | IPA] BeatSaberMarkupLanguage (BeatSaberMarkupLanguage): 1.6.3
[INFO @ 19:51:12 | IPA] PracticePlugin (PracticePlugin): 6.0.9
[INFO @ 19:51:12 | IPA] INI Parser (Ini Parser): 2.5.9
[INFO @ 19:51:12 | IPA] BS_Utils (BS Utils): 1.12.0
[INFO @ 19:51:12 | IPA] SongCore (SongCore): 3.9.5
[INFO @ 19:51:12 | IPA] BeatSaverSharp (BeatSaverSharp): 3.4.2
[INFO @ 19:51:12 | IPA] ScoreSaberSharp (ScoreSaberSharp): 0.1.0
[INFO @ 19:51:12 | IPA] BeatSaver Downloader (BeatSaverDownloader): 5.8.2
[INFO @ 19:51:12 | IPA] DynamicOpenVR (DynamicOpenVR): 0.4.0
[INFO @ 19:51:12 | IPA] Custom Avatars (CustomAvatar): 5.2.11
[INFO @ 19:51:12 | IPA] JDFixer (JDFixer): 5.0.2
[INFO @ 19:51:12 | IPA] BeatSaberPlus (BeatSaberPlusCORE): 4.3.1
[INFO @ 19:51:12 | IPA] BeatSaberPlus_Chat (BeatSaberPlus_Chat): 4.3.1
[INFO @ 19:51:12 | IPA] Intro Skip (IntroSkip): 4.0.3
[INFO @ 19:51:12 | IPA] SaberTailor (SaberTailor): 3.5.0
[INFO @ 19:51:12 | IPA] ScoreSaber (ScoreSaber): 3.2.8
[INFO @ 19:51:12 | IPA] protobuf-net (protobuf-net): 3.0.102
[INFO @ 19:51:12 | IPA] Song Request Manager (SongRequestManager): 2.15.8
[INFO @ 19:51:12 | IPA] CustomNotes (Custom Notes): 2.6.1
[INFO @ 19:51:12 | IPA] CustomJSONData (CustomJSONData): 2.2.3
[INFO @ 19:51:12 | IPA] Heck (_Heck): 1.3.6
[INFO @ 19:51:12 | IPA] LookupID (LookupID): 1.0.1
[INFO @ 19:51:12 | IPA] Chroma (Chroma): 2.5.11
[INFO @ 19:51:12 | IPA] Saber Factory (SaberFactory): 2.5.1
[INFO @ 19:51:12 | IPA] BeatSaverVoting (BeatSaverVoting): 2.3.5
[INFO @ 19:51:12 | IPA] ImageCoverExpander (ImageCoverExpander): 2.3.5
[INFO @ 19:51:12 | IPA] Counters+ (Counters+): 2.2.7
[INFO @ 19:51:12 | IPA] FastFail (FastFail): 2.0.5
[INFO @ 19:51:12 | IPA] ImageSharp (SixLabors.ImageSharp): 2.0.0
[INFO @ 19:51:12 | IPA] Particle Overdrive (Particle Overdrive): 1.12.0
[INFO @ 19:51:12 | IPA] MappingExtensions (MappingExtensions): 1.7.2
[INFO @ 19:51:12 | IPA] BetterSongList (BetterSongList): 0.3.0
[INFO @ 19:51:12 | IPA] BeatSaberPlaylistsLib (BeatSaberPlaylistsLib): 1.6.6
[INFO @ 19:51:12 | IPA] PlaylistManager (PlaylistManager): 1.6.5
[INFO @ 19:51:12 | IPA] ScorePercentage (ScorePercentage): 1.4.12
[INFO @ 19:51:12 | IPA] SongDetailsCache (SongDetailsCache): 1.2.1
[INFO @ 19:51:12 | IPA] BeatSaverUpdater (BeatSaverUpdater): 1.1.0
[INFO @ 19:51:12 | IPA] RumbleMod (RumbleMod): 1.0.9
[INFO @ 19:51:12 | IPA] Technicolor (Technicolor): 1.0.9
[INFO @ 19:51:12 | IPA] AdBlocker (AdBlocker): 1.0.4
[INFO @ 19:51:12 | IPA] CatCore (CatCore): 1.0.0
[INFO @ 19:51:12 | IPA] Link (Link): 1.0.3
[INFO @ 19:51:12 | IPA] BetterSongSearch (BetterSongSearch): 0.7.2
[INFO @ 19:51:12 | IPA] Camera2 (Camera2): 0.6.91
[INFO @ 19:51:12 | IPA] Arcgap (Arcgap): 0.0.5
[INFO @ 19:51:12 | IPA] BSIndexHapticFix (BSIndexHapticFix): 0.0.2
[INFO @ 19:51:12 | IPA] MaybeStutterFix (MaybeStutterFix): 0.0.1

**Comment by ErisApps** [comment]
Will look into it.

**Comment by ErisApps** [comment]
This should (hopefully) be fixed by #46, which will normally be released later this week if no other issues occur during testing.
