### ISSUE TITLE
i cant see the chat.

### ISSUE THREAD

**Issue by DeagleVR** [ErisApps/ChatCore#51]
when i downloaded the mod and i go in game i dont see it.

**Comment by ErisApps** [comment]
Hii, as mentioned on the main README, the wiki and in the release notes. This library does nothing on its own and requires other mods/plugins/applications to make use of the features it provides.
That being said, assuming that you're looking for in-game chat for Beat Saber, I recommend you to use this mod though: https://github.com/denpadokei/EnhancedStreamChat-v3/releases/5.0.4
