### ISSUE TITLE
Latest version (1.1.0) not available on release page?

### ISSUE THREAD

**Issue by coolfarmer** [ErisApps/ChatCore#77]
Hi,

Is there a reason why the release page has not been updated with the latest version (1.1.0)? I also tried using the Mod Assistant software, but I couldn't find the mod for Beat Saber V1.28.

What can I do to download version 1.1.0?

Please note: I'm using Beat Saber with the Oculus Software, not Steam.

Thank you!

**Comment by ErisApps** [comment]
Hii,

I tried to break down your issue into several questions, feel free to let me know if anything was unclear.

> Is there a reason why the release page has not been updated with the latest version (1.1.0)?

Haven't released the version just yet as I'm still in the process of validating that everything still works as intended, which can be pretty time consuming. However, CatCore is a library that isn't dependent on the game whatsoever so you can use 1.0.1 without any repercussions. ^^

> I also tried using the Mod Assistant software, but I couldn't find the mod for Beat Saber V1.28.

It still needs to be approved for this game version version on ModAssistant. Also keep in mind that the approval process is a multi-stage process, which includes both reviewing of code and in-game testing, and is therefor also relatively time-consuming.
Also, as I'm part of the approval staff for Beatmods/ModAssistant myself, I'm obviously not allowed to approve my own mods/libraries so it basically depends on whether others of the approval staff have time. 
*Also hoping that happens soon myself.* 😅

> What can I do to download version 1.1.0?

As I'm still in the process of verifying the correct working of the library, I'd rather suggest that you fall back to version 1.0.1 of the library until I officially release 1.1.0.
That being said, if you *really* can't wait, you might be able to grab it from the GH Actions pipeline, but I keep in mind that I, _despite really wanting to,_ can't give any guarantees that everything will work flawlessly right now.

> Please note: I'm using Beat Saber with the Oculus Software, not Steam.

As mentioned in the reply to the first question, CatCore is completely game-agnostic so it literally doesn't care whether you're running it though Oculus or Steam, nor does it care about what version it is used on. That being said, the mods that actually use CatCore under the hood mostly do care about the game version. 😅

Hope you have a nice day ^^

**Comment by coolfarmer** [comment]
Great answer, thank you for taking the time to clarify this! :)

**Comment by ErisApps** [comment]
@coolfarmer Just fyi, but CatCore 1.0.1 has been approved on Mod Assistant just now and version 1.1.0 got released (with release notes) on the release page. Feel free to pick the version of your choice.
